- name: Ensure git is installed
  become: yes
  package:
    name: git
    state: present
    use: apt

- name: Set project path
  set_fact:
    project_path: "{{ base_path }}/{{ project_name }}"

- name: Create project directory
  file:
    path: "{{ project_path }}"
    state: directory

- name: Set global Git user name
  git_config:
    name: user.name
    value: "{{ git_username }}"
    scope: global

- name: Set global Git user email
  git_config:
    name: user.email
    value: "{{ git_email }}"
    scope: global

- name: Attempt to clone repository
  git:
    repo: "{{ mkdocs_repo_url }}"
    dest: "{{ project_path }}"
    force: yes
    key_file: /home/matts/.ssh/id_rsa
  register: git_clone
  ignore_errors: yes

- name: Create mkdocs docs directory
  file:
    path: "{{ project_path }}/docs"
    state: directory
  when: git_clone.failed

- name: Initialize the local Git repository if clone failed
  command: git init
  args:
    chdir: "{{ project_path }}"
  when: git_clone.failed

- name: Create gitignore
  copy:
    dest: "{{ project_path }}/.gitignore"
    content: |
      venv/
  when: git_clone.failed

- name: Commit an empty commit to the main branch if just created
  command: git commit --allow-empty -m "Initial commit"
  args:
    chdir: "{{ project_path }}"
  when: git_clone.failed

- name: Create the main branch if it doesn't exist
  command: git branch -M main
  args:
    chdir: "{{ project_path }}"
  when: git_clone.failed

- name: Add remote repository 
  command: git remote add origin {{ mkdocs_repo_url }}
  args:
    chdir: "{{ project_path }}"
  when: git_clone.failed

- name: Push the main branch if just created
  command: git push -u origin main
  args:
    chdir: "{{ project_path }}"
  when: git_clone.failed
