---

- name: Create mkdocs directory
  include_tasks: create_mkdocs_dir.yml

- name: Create directory for common images
  file:
    path: "{{ base_path }}/{{project_name}}/docs/common_images"
    state: directory

- name: Include task to create directories/files for each system, subsystem, and component
  include_tasks: system_dirs_files.yml
  loop: "{{ systems }}"
  loop_control:
    loop_var: system_item
  tags:
      - update_project_systems
      - update_project_template

- name: Include task to create directories/files for each requirement
  include_tasks: requirements_dirs_files.yml
  vars:
    requirements_type: "{{ item }}"
  loop:
    - functional
    - security
  tags:
      - update_project_systems
      - update_project_template


- name: Install Packages
  include_tasks: package_install.yml

- name: Template the mkdocs.yml file
  template:
    src: templates/mkdocs.yml.j2
    dest: "{{ base_path }}/{{project_name}}/mkdocs.yml"
  tags: 
    - update_project_mkdocs_template
    - update_project_systems

- name: Push project repo
  include_tasks: update_project_repo.yml
  tags: push_project_update

- name: Include update_project_template tasks
  include_tasks: update_project_templates.yml
  tags:
    - update_project_template  # This ensures the inclusion task itself is always considered
