---

- name: Create mkdocs directory
  include_tasks: create_mkdocs_dir.yml

- name: Create directory for common images
  file:
    path: "{{ base_path }}/{{project_name}}/docs/common_images"
    state: directory
  tags: create_images_dir

- name: Include task to create directories/files for each system, subsystem, and component
  include_tasks: system_dirs_files.yml
  loop: "{{ systems }}"
  loop_control:
    loop_var: system_item
  tags: mkdocs_template_update

- name: Install Packages
  include_tasks: package_install.yml

- name: Template the mkdocs.yml file
  template:
    src: templates/mkdocs.yml.j2
    dest: "{{ base_path }}/{{project_name}}/mkdocs.yml"
  tags: mkdocs_template_update

- name: Push project repo
  include_tasks: update_mkdocs_repo.yml