- name: Ensure Python3 pip is present
  become: yes
  apt:
    name: python3-pip
    state: present

- name: Create a virtual environment for mkdocs and plugins
  become: yes
  ansible.builtin.command:
    cmd: python3 -m venv {{ base_path }}/{{ project_name }}/venv
  args:
    creates: "{{ base_path }}/{{ project_name }}/venv"

- name: Install required packages
  become: yes
  apt:
    name:
      - python3-pip
      - wget
      - curl
      - desktop-file-utils
      - libasound2
      - xvfb
    state: present

- name: Create a virtual environment for mkdocs and plugins
  become: yes
  ansible.builtin.command:
    cmd: python3 -m venv {{ base_path }}/{{ project_name }}/venv
  args:
    creates: "{{ base_path }}/{{ project_name }}/venv"

- name: Install mkdocs and plugins
  become: yes
  pip:
    name:
      - mkdocs
      - mkdocs-material
      - mkdocs-drawio-exporter
      - mkdocs-macros-plugin
      - mkdocs-include-markdown-plugin
    state: present
    executable: "{{ base_path }}/{{ project_name }}/venv/bin/pip3"

- name: Install draw.io
  block:
    - name: Update and upgrade APT packages
      become: yes
      apt:
        update_cache: yes
        upgrade: yes

    - name: Check if draw.io is installed
      ansible.builtin.command: which drawio
      register: drawio_installed
      ignore_errors: yes

    - name: Get the latest draw.io release URL and download .deb package
      become: yes
      ansible.builtin.shell: |
        curl -s https://api.github.com/repos/jgraph/drawio-desktop/releases/latest | 
        grep browser_download_url | 
        grep '\.deb' | 
        cut -d '"' -f 4 | 
        wget -i - -O /tmp/drawio-amd64.deb
      args:
        executable: /bin/bash
      register: wget_output
      failed_when: wget_output.rc != 0 or 'No such file' in wget_output.stderr
      when: drawio_installed is failed

    - name: Ensure desktop-file-utils is installed
      become: yes
      apt:
        name: desktop-file-utils
        state: present

    - name: Install draw.io package using dpkg
      become: yes
      ansible.builtin.command:
        cmd: "dpkg -i /tmp/drawio-amd64.deb"
      register: dpkg_result
      failed_when: "'Errors were encountered while processing' in dpkg_result.stderr or dpkg_result.rc != 0"
      changed_when: "'Setting up draw.io' in dpkg_result.stdout or 'Unpacking draw.io' in dpkg_result.stdout"
      ignore_errors: yes
      when: drawio_installed is failed

    - name: Verify draw.io installation
      become: yes
      command: dpkg -s draw.io
      register: verify_install
      changed_when: false

    - name: Output installation verification
      debug:
        var: verify_install.stdout_lines

    - name: Install additional required packages
      become: yes
      apt:
        name:
          - libasound2
          - xvfb
        state: present
