---

- name: Update apt cache and install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes
  become: yes

- name: Ensure git is installed
  become: yes
  package:
    name: git
    state: present
    use: apt
  become: yes

- name: Set project path
  set_fact:
    project_path: "{{ base_path }}/{{ project_name }}"

- name: Create project directory
  file:
    path: "{{ project_path }}"
    state: directory

- name: Set global Git user name
  git_config:
    name: user.name
    value: "{{ git_username }}"
    scope: global

- name: Set global Git user email
  git_config:
    name: user.email
    value: "{{ git_email }}"
    scope: global

- name: Attempt to clone repository
  git:
    repo: "{{ mkdocs_repo_url }}"
    dest: "{{ project_path }}"
    force: yes
    key_file: /home/matts/.ssh/id_rsa
  register: git_clone
  tags: push_project_update

- name: Apply Nginx template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
  become: yes

- name: Enable new site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: restart nginx
  become: yes

- name: Allow all access to tcp port 8080
  ufw:
    rule: allow
    port: '8080'
    proto: tcp
  become: yes