- name: Create directory for component
  file:
    path: "{{ base_path }}/{{project_name}}/docs/{{ system_item.name }}/{{ subsystem_item.name }}/{{ component_item.name }}"
    state: directory

- name: Create supporting directory for compontent
  file:
    path: "{{ base_path }}/{{project_name}}/docs/{{ system_item.name }}/{{ subsystem_item.name }}/{{ component_item.name }}/{{ item }}"
    state: directory
  loop: "{{ supporting_folders }}"