- name: Create directory for system
  file:
    path: "{{ base_path }}/{{project_name}}/docs/{{ system_item.name }}"
    state: directory

- name: Create directory for common images
  template:
    src: "templates/system_detailed_design.md.j2"
    dest: "{{ base_path }}/{{project_name}}/docs/{{ system_item.name }}/{{ system_item.name }}-detailed_design.md"
  tags:
    - rerun_system_dirs

- name: Create system details design file
  file:
    path: "{{ base_path }}/{{project_name}}/docs/{{ system_item.name }}"
    state: directory

- name: Include task to create directories for each subsystem
  include_tasks: create_subsystem_dirs.yml
  loop: "{{ system_item.subsystems | default([]) }}"
  loop_control:
    loop_var: subsystem_item
  when: subsystem_item is defined