- name: Create directory for subsystem
  file:
    path: "{{ base_path }}/{{project_name}}/docs/{{ system_item.name }}/{{ subsystem_item.name }}"
    state: directory

- name: Create subsystem detail design file
  template:
    src: "templates/subsystem_detailed_design.md.j2"
    dest: "{{ base_path }}/{{project_name}}/docs/{{ system_item.name }}/{{ subsystem_item.name }}/{{ subsystem_item.name }}-detailed_design.md"
  tags:
    - rerun_system_dirs

- name: Create supporting directory for subsystem
  file:
    path: "{{ base_path }}/{{project_name}}/docs/{{ system_item.name }}/{{ subsystem_item.name }}/{{ item }}"
    state: directory
  loop: "{{ supporting_folders }}"


- name: Include task to create directories for each component
  include_tasks: create_component_dirs.yml
  loop: "{{ subsystem_item.components | default([]) }}"
  loop_control:
    loop_var: component_item
  when: component_item is defined
