---
- name: Create Nested Directories
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/mkdocs_build.yml
    - vars/sos_master.yml
    - vars/requirements.yml
    - vars/secret.yml

  tasks:

    - name: Create mkdocs directory
      include_tasks: tasks/create_mkdocs_dir.yml

    - name: Create directory for common images
      file:
        path: "{{ base_path }}/{{project_name}}/docs/common_images"
        state: directory
      tags: create_images_dir

    - name: Include task to create directories/files for each system,subsystem and compontent
      include_tasks: tasks/system_dirs_files.yml
      loop: "{{ systems }}"
      loop_control:
        loop_var: system_item
      tags: rerun_system_dirs

    - name: Install Packages
      include_tasks: tasks/package_install.yml

    - name: Template the mkdocs.yml file
      template:
        src: ./templates/mkdocs.yml.j2
        dest: "{{ base_path }}/{{project_name}}/mkdocs.yml"
      tags: mkdocs_template