---
- name: Create Nested Directories
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/mkdocs_build.yml
    - vars/sos_master.yml
    - vars/requirements.yml
    - secret.yml
  vars:
    base_path: "./"  # Define your base path here

  tasks:

    - name: Create mkdocs directory
      include_tasks: create_mkdocs_dir.yml

    - name: Install Packages
      include_tasks: package_install.yml

    - name: Include task to create directories/files for each system,subsystem and compontent
      include_tasks: create_system_dirs.yml
      loop: "{{ systems }}"
      loop_control:
        loop_var: system_item

    - name: Template the mkdocs.yml file
      template:
        src: ./templates/mkdocs.yml.j2
        dest: mkdocs.yml