- name: Check if remote repository exists
  command: git ls-remote {{ mkdocs_repo_url }}
  register: remote_repo_exists
  ignore_errors: yes


- name: Add all files in directory to git tracking
  command: git add .
  args:
    chdir: "{{ project_path }}"

- name: Commit change
  command: git commit --allow-empty -m "new update"


- name: Push update to remote repository
  command: git push 
  args:
    chdir: "{{ project_path }}"
  register: git_push
  ignore_errors: yes


